spec:
  template:
    spec:
      containers:
        - readinessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            failureThreshold: 3
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            failureThreshold: 2
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 500Mi
          volumeMounts:
            - name: config
              mountPath: /app/config
            - name: rhsso-config
              mountPath: /app/rhsso-config
          env:
            - name: JAVA_OPTIONS
              value: "-Dswarm.project.stage.file=file:///app/config/project-defaults.yml -Dswarm.keycloak.json.path=/app/rhsso-config/keycloak.json -Dcom.redhat.coolstore.inventory.service.StoreStatusService/storeStatus/CircuitBreaker/requestVolumeThreshold=4 -Dcom.redhat.coolstore.inventory.service.StoreStatusService/storeStatus/CircuitBreaker/requestVolumeThreshold=2 -Dcom.redhat.coolstore.inventory.service.StoreStatusService/storeStatus/CircuitBreaker/failureRatio=1 -Dcom.redhat.coolstore.inventory.service.StoreStatusService/storeStatus/Timeout/value=250"
            - name: GC_MAX_METASPACE_SIZE
              value: '200'
        - name: jaeger-agent
          image: jaeger-agent
          command:
            - /go/bin/agent-linux
            - '--reporter.type=tchannel'
            - '--reporter.tchannel.host-port=jaeger-collector.user3-coolstore-infra.svc:14267'
          ports:
            - containerPort: 5775
              protocol: UDP
            - containerPort: 5778
              protocol: TCP
            - containerPort: 6831
              protocol: UDP
            - containerPort: 6832
              protocol: UDP
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 100Mi
      volumes:
        - configMap:
            name: inventory-service
          name: config
        - configMap:
            name: inventory-service-rhsso
          name: rhsso-config
